kind: pipeline
type: docker
name: default

steps:
  - name: build
    image: node:20.15.1
    commands:
      - npm install
  #     - npm run build

  # - name: publish
  #   image: plugins/docker
  #   settings:
  #     repo: monsaiya/monsaiya
  #     username:
  #       from_secret: docker_username
  #     password:
  #       from_secret: docker_password
  #     tags: latest

  - name: publish
    image: plugins/ecr:20.18
    settings:
      access_key:
        from_secret: ecr_access_key
      secret_key:
        from_secret: ecr_secret_key
      repo:
        from_secret: ecr_repo
      registry:
        from_secret: ecr_registry
      region:
        from_secret: ecr_region
      tags:
        - latest

trigger:
  branch:
    - main
