kind: pipeline
type: docker
name: default

steps:
  - name: build
    image: node:16-alpine
    commands:
      - npm install
      - npm run build
      - docker build -t monsaiya/monsaiya:latest .

  - name: publish
    image: plugins/docker
    settings:
      repo: monsaiya/monsaiya
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      tags: latest

trigger:
  event:
    - push
  branch:
    - main
